// the variable values can be accessed from other variable.js file
console.log(firstName, lastName, country, city, age, isMarried) 
console.log(gravity, boilingPoint, PI) // 9.81, 100, 3.14
console.log(name, job, live)
console.log(challenge)
console.log(challenge.length)
console.log(challenge.toUpperCase())
console.log(challenge.toLowerCase())
console.log(challenge.substring(0, 3))
console.log(challenge.substring(0, 3), challenge.substring(3, 8), challenge.substring(8, 10), challenge.substring(10, 21))
console.log(challenge.includes('Script'))
console.log(challenge.split(''))
console.log('Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'.split(','))
console.log('30 Days Of JavaScript'.replace('JavaScript','Python'))
console.log(challenge.charAt(15))
console.log(challenge.charAt(11), challenge.charCodeAt(challenge.indexOf('J')))
console.log('First a', challenge.indexOf('a'))
console.log('Last a', challenge.lastIndexOf('a'))
console.log('You cannot end a sentence with because because because is a conjunction', 'You cannot end a sentence with because because because is a conjunction'.indexOf('because'))
console.log('You cannot end a sentence with because because because is a conjunction', 'You cannot end a sentence with because because because is a conjunction'.search('because'))
console.log(' 30 Days Of JavaScript ', ' 30 Days Of JavaScript '.trim())
console.log('30 Days Of JavaScript', '30 Days Of JavaScript'.startsWith('30'))
console.log('30 Days Of JavaScript', '30 Days Of JavaScript'.endsWith('Script'))
console.log('30 Days Of JavaScript', '30 Days Of JavaScript'.match(pattern))
console.log('30 Days Of ', '30 Days Of '.concat('JavaScript'))
console.log('30 Days Of JavaScript '.repeat(2))